/**
 * Códigos LADA (prefijo de país) para el selector de teléfono.
 * Formato: +[código] para uso en E.164.
 */
export const COUNTRY_CODES: { code: string; country: string }[] = [
  { code: "+52", country: "México" },
  { code: "+1", country: "Estados Unidos / Canadá" },
  { code: "+34", country: "España" },
  { code: "+54", country: "Argentina" },
  { code: "+57", country: "Colombia" },
  { code: "+58", country: "Venezuela" },
  { code: "+51", country: "Perú" },
  { code: "+56", country: "Chile" },
  { code: "+593", country: "Ecuador" },
  { code: "+591", country: "Bolivia" },
  { code: "+598", country: "Uruguay" },
  { code: "+595", country: "Paraguay" },
  { code: "+53", country: "Cuba" },
  { code: "+502", country: "Guatemala" },
  { code: "+503", country: "El Salvador" },
  { code: "+504", country: "Honduras" },
  { code: "+505", country: "Nicaragua" },
  { code: "+506", country: "Costa Rica" },
  { code: "+507", country: "Panamá" },
  { code: "+55", country: "Brasil" },
  { code: "+44", country: "Reino Unido" },
  { code: "+33", country: "Francia" },
  { code: "+49", country: "Alemania" },
  { code: "+39", country: "Italia" },
  { code: "+31", country: "Países Bajos" },
  { code: "+32", country: "Bélgica" },
  { code: "+41", country: "Suiza" },
  { code: "+43", country: "Austria" },
  { code: "+46", country: "Suecia" },
  { code: "+47", country: "Noruega" },
  { code: "+45", country: "Dinamarca" },
  { code: "+358", country: "Finlandia" },
  { code: "+353", country: "Irlanda" },
  { code: "+351", country: "Portugal" },
  { code: "+48", country: "Polonia" },
  { code: "+7", country: "Rusia" },
  { code: "+81", country: "Japón" },
  { code: "+86", country: "China" },
  { code: "+82", country: "Corea del Sur" },
  { code: "+91", country: "India" },
  { code: "+61", country: "Australia" },
  { code: "+64", country: "Nueva Zelanda" },
  { code: "+27", country: "Sudáfrica" },
  { code: "+972", country: "Israel" },
  { code: "+971", country: "Emiratos Árabes Unidos" },
  { code: "+90", country: "Turquía" },
  { code: "+20", country: "Egipto" },
  { code: "+234", country: "Nigeria" },
  { code: "+254", country: "Kenia" },
  { code: "+62", country: "Indonesia" },
  { code: "+65", country: "Singapur" },
  { code: "+66", country: "Tailandia" },
  { code: "+84", country: "Vietnam" },
  { code: "+63", country: "Filipinas" },
  { code: "+60", country: "Malasia" },
  { code: "+973", country: "Baréin" },
  { code: "+966", country: "Arabia Saudita" },
  { code: "+974", country: "Catar" },
  { code: "+968", country: "Omán" },
  { code: "+965", country: "Kuwait" },
];

export const DEFAULT_COUNTRY_CODE = "+52";
