/**
 * Códigos LADA (prefijo de país) para el selector de teléfono.
 * Formato: +[código] para uso en E.164.
 * short: abreviatura mostrada en el dropdown (ej. mx, us, arg).
 */
export const COUNTRY_CODES: { code: string; country: string; short: string }[] = [
  { code: "+52", country: "México", short: "mx" },
  { code: "+1", country: "Estados Unidos / Canadá", short: "us" },
  { code: "+34", country: "España", short: "es" },
  { code: "+54", country: "Argentina", short: "arg" },
  { code: "+57", country: "Colombia", short: "co" },
  { code: "+58", country: "Venezuela", short: "ve" },
  { code: "+51", country: "Perú", short: "pe" },
  { code: "+56", country: "Chile", short: "cl" },
  { code: "+593", country: "Ecuador", short: "ec" },
  { code: "+591", country: "Bolivia", short: "bo" },
  { code: "+598", country: "Uruguay", short: "uy" },
  { code: "+595", country: "Paraguay", short: "py" },
  { code: "+53", country: "Cuba", short: "cu" },
  { code: "+502", country: "Guatemala", short: "gt" },
  { code: "+503", country: "El Salvador", short: "sv" },
  { code: "+504", country: "Honduras", short: "hn" },
  { code: "+505", country: "Nicaragua", short: "ni" },
  { code: "+506", country: "Costa Rica", short: "cr" },
  { code: "+507", country: "Panamá", short: "pa" },
  { code: "+55", country: "Brasil", short: "br" },
  { code: "+44", country: "Reino Unido", short: "uk" },
  { code: "+33", country: "Francia", short: "fr" },
  { code: "+49", country: "Alemania", short: "de" },
  { code: "+39", country: "Italia", short: "it" },
  { code: "+31", country: "Países Bajos", short: "nl" },
  { code: "+32", country: "Bélgica", short: "be" },
  { code: "+41", country: "Suiza", short: "ch" },
  { code: "+43", country: "Austria", short: "at" },
  { code: "+46", country: "Suecia", short: "se" },
  { code: "+47", country: "Noruega", short: "no" },
  { code: "+45", country: "Dinamarca", short: "dk" },
  { code: "+358", country: "Finlandia", short: "fi" },
  { code: "+353", country: "Irlanda", short: "ie" },
  { code: "+351", country: "Portugal", short: "pt" },
  { code: "+48", country: "Polonia", short: "pl" },
  { code: "+7", country: "Rusia", short: "ru" },
  { code: "+81", country: "Japón", short: "jp" },
  { code: "+86", country: "China", short: "cn" },
  { code: "+82", country: "Corea del Sur", short: "kr" },
  { code: "+91", country: "India", short: "in" },
  { code: "+61", country: "Australia", short: "au" },
  { code: "+64", country: "Nueva Zelanda", short: "nz" },
  { code: "+27", country: "Sudáfrica", short: "za" },
  { code: "+972", country: "Israel", short: "il" },
  { code: "+971", country: "Emiratos Árabes Unidos", short: "ae" },
  { code: "+90", country: "Turquía", short: "tr" },
  { code: "+20", country: "Egipto", short: "eg" },
  { code: "+234", country: "Nigeria", short: "ng" },
  { code: "+254", country: "Kenia", short: "ke" },
  { code: "+62", country: "Indonesia", short: "id" },
  { code: "+65", country: "Singapur", short: "sg" },
  { code: "+66", country: "Tailandia", short: "th" },
  { code: "+84", country: "Vietnam", short: "vn" },
  { code: "+63", country: "Filipinas", short: "ph" },
  { code: "+60", country: "Malasia", short: "my" },
  { code: "+973", country: "Baréin", short: "bh" },
  { code: "+966", country: "Arabia Saudita", short: "sa" },
  { code: "+974", country: "Catar", short: "qa" },
  { code: "+968", country: "Omán", short: "om" },
  { code: "+965", country: "Kuwait", short: "kw" },
];

export const DEFAULT_COUNTRY_CODE = "+52";
